// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ".Configurator .options {\n  display: grid;\n  grid-auto-columns: min-content auto;\n  grid-gap: 1px;\n  overflow: hidden;\n  border: 1px solid #626d80;\n  border-radius: 4px;\n  background-color: #1C212B;\n}\n\nbutton {\n  padding: 5px 10px;\n  color: #626d80;\n  background-color: #0B0E14;\n  border: none;\n  border-radius: 5px;\n  outline: none;\n  transition: filter .15s ease;\n  margin: 5px 5px 5px 0;\n}\n\nbutton:hover {\n  filter: brightness(1.5);\n}\n\nselect {\n  padding: 4px 7px;\n  color: #626d80;\n  background-color: #0B0E14;\n  border: none;\n  border-radius: 5px;\n  margin-top: 5px;\n  margin-right: 7px;\n  outline: none;\n  transition: filter .15s ease-in;\n}\n\nselect:focus {\n  filter: brightness(1.2);\n  filter: contrast(1.4);\n}\n\ninput {\n  padding: 4px 7px;\n  color: #626d80;\n  background-color: #0B0E14;\n  border: none;\n  border-radius: 5px;\n  margin-top: 5px;\n  margin-right: 7px;\n  outline: none;\n  transition: color .15s ease-in, background-color .15s ease-out;\n}\n\ninput:focus {\n  background-color: #626d80;\n  color: #0B0E14;\n}\n\n.Configurator .options > h2 {\n  grid-column: 1;\n  margin: 0;\n  padding: 8px 24px 8px 8px;\n  white-space: nowrap;\n  text-align: center;\n  font-size: 16px;\n  font-weight: 600;\n  color: #bdbdbd;\n  box-shadow: 0 0 0 1px #626d80;\n}\n\n.Configurator .options > .control {\n  grid-column: 2;\n  padding: 8px;\n  box-shadow: 0 0 0 1px #626d80;\n}\n\n.Configurator label {\n  display: block;\n  padding: 0 0 8px;\n}\n\n.Configurator .result {\n  margin-top: 16px;\n  width: 100%;\n  color: #AAD94C;\n  background-color: #11151C;\n  padding: 8px 8px 0 8px;\n  outline: none;\n  resize: none;\n  border-radius: 4px;\n  border: none;\n  cursor: copy;\n}\n\n.copyText { \n  margin-top: 2px;\n  text-align: center;\n  font-weight: 600;\n}\n\n.Configurator .result::-webkit-scrollbar {\n  width: 10px;\n  height: 5px;\n  background-color: #8a9199; /* or add it to the track */\n}\n\n.Configurator .result::-webkit-scrollbar-thumb {\n  background: #0D1017;\n}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}